# Use official Node.js image as base
FROM node:14

# Set working directory
WORKDIR /app/backend

# Copy package.json and package-lock.json
COPY ./package*.json ./

# Install dependencies
RUN npm install

# Copy backend source code
COPY . .

# Expose port 5000
EXPOSE 5000

# Command to run the backend server
CMD ["npm", "start"]